EmailApi with query and params use
sahilbhatia/node-js-training pull request #27
Opened 2020-03-16 08:29 UTC by jitendrasbunde

2020-03-16 10:26 UTC, sunil4sonawane commented on emailApi/email.js
> +			pass :'gawgialpaiqhongo'
remove password

2020-03-16 10:26 UTC, sunil4sonawane commented on emailApi/emailApi.js
> +module.exports = router;
add new line

2020-03-16 10:27 UTC, sunil4sonawane commented on emailApi/index.js
> +);
add new line

2020-03-16 10:27 UTC, sunil4sonawane requested changes
Check comments

2020-03-16 11:11 UTC, jitendrasbunde commented on emailApi/email.js
> +			pass :'gawgialpaiqhongo'
means sir i don't get it

2020-03-17 08:05 UTC, sunil4sonawane requested changes
You have raised this against master. please change it

2020-03-17 12:19 UTC, closed without merging